-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."GroupClaims"
(
    "GroupId" integer NOT NULL,
    "ClaimId" integer NOT NULL,
    PRIMARY KEY ("GroupId", "ClaimId")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Groups"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GroupName" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Languages"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(10) NOT NULL,
    "Code" character varying(10) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Logs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MessageTemplate" text,
    "Level" text,
    "TimeStamp" timestamp with time zone NOT NULL,
    "Exception" text,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."OperationClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(50) NOT NULL,
    "Alias" character varying(50),
    "Description" character varying(100),
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Translates"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "LangId" integer NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Value" character varying(500) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."UserClaims"
(
    "UsersId" integer NOT NULL,
    "ClaimId" integer NOT NULL,
    "Id" bigint NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."UserGroups"
(
    "GroupId" integer NOT NULL,
    "UserId" integer NOT NULL,
    PRIMARY KEY ("UserId", "GroupId")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Users"
(
    "UserId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "MobilePhones" character varying(30),
    "Status" boolean NOT NULL,
    "RecordDate" timestamp without time zone NOT NULL,
    "Notes" character varying(500),
    "UpdateContactDate" timestamp without time zone NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "ResetPasswordExpires" timestamp without time zone,
    "ResetPasswordToken" character varying(500),
    PRIMARY KEY ("UserId")
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public."GroupClaims"
    ADD FOREIGN KEY ("ClaimId")
    REFERENCES public."OperationClaims" ("Id")
    NOT VALID;


ALTER TABLE public."GroupClaims"
    ADD FOREIGN KEY ("GroupId")
    REFERENCES public."Groups" ("Id")
    NOT VALID;


ALTER TABLE public."Translates"
    ADD FOREIGN KEY ("LangId")
    REFERENCES public."Languages" ("Id")
    NOT VALID;


ALTER TABLE public."UserClaims"
    ADD FOREIGN KEY ("ClaimId")
    REFERENCES public."OperationClaims" ("Id")
    NOT VALID;


ALTER TABLE public."UserClaims"
    ADD FOREIGN KEY ("UsersId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."UserGroups"
    ADD FOREIGN KEY ("GroupId")
    REFERENCES public."Groups" ("Id")
    NOT VALID;


ALTER TABLE public."UserGroups"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;

END;