apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  namespace: service-app-dev
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: auth-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server 
  namespace: service-app-dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-server 
  template:
    metadata:
      labels:
        app: auth-server 
    spec:
      volumes:
        - name: appconfig
          secret:
            secretName: auth-service-secret
            items:
            - key: appsettings.json
              path: appsettings.json
      containers:
        - name: auth-server 
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100M"
              cpu: "0.02"
            limits:
              memory: "200M"
              cpu: "0.05"
          volumeMounts:
          - name: appconfig
            mountPath: /app/appsettings.json
            subPath: appsettings.json
          ports:
            - name: http-port
              containerPort: 8000
              hostPort: 8000
          livenessProbe:
            httpGet:
              path: /api/HealthChecks/get
              port: 8000
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 60
            periodSeconds: 5
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false


